# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Login_funcionario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        MainWindow.setStyleSheet("background-color: rgb(242, 242, 243);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_cabecalho = QtWidgets.QFrame(self.centralwidget)
        self.login_cabecalho.setMinimumSize(QtCore.QSize(0, 50))
        self.login_cabecalho.setMaximumSize(QtCore.QSize(16777215, 50))
        self.login_cabecalho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_cabecalho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_cabecalho.setObjectName("login_cabecalho")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.login_cabecalho)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.login_cabecalho)
        self.label.setMinimumSize(QtCore.QSize(170, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"text-align: center;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.login_cabecalho)
        self.login_conteudo = QtWidgets.QFrame(self.centralwidget)
        self.login_conteudo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_conteudo.setObjectName("login_conteudo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_conteudo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.login_conteudo)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.login_lineEdit_cpf = QtWidgets.QLineEdit(self.frame_4)
        self.login_lineEdit_cpf.setMinimumSize(QtCore.QSize(250, 30))
        self.login_lineEdit_cpf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.login_lineEdit_cpf.setStyleSheet("border-width: 1px;\n"
"border-color: black;\n"
"border-style: solid;\n"
"display: inline-block;\n"
"border-radius: 5px;")
        self.login_lineEdit_cpf.setInputMask("")
        self.login_lineEdit_cpf.setText("")
        self.login_lineEdit_cpf.setObjectName("login_lineEdit_cpf")
        self.verticalLayout_4.addWidget(self.login_lineEdit_cpf)
        self.login_lineEdit_senha = QtWidgets.QLineEdit(self.frame_4)
        self.login_lineEdit_senha.setMinimumSize(QtCore.QSize(0, 30))
        self.login_lineEdit_senha.setStyleSheet("border-width: 1px;\n"
"border-color: black;\n"
"border-style: solid;\n"
"display: inline-block;\n"
"border-radius: 5px;")
        self.login_lineEdit_senha.setInputMask("")
        self.login_lineEdit_senha.setText("")
        # Ocultar senha
        self.login_lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)

        self.login_lineEdit_senha.setObjectName("login_lineEdit_senha")
        self.verticalLayout_4.addWidget(self.login_lineEdit_senha)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.login_confirmacao = QtWidgets.QFrame(self.login_conteudo)
        self.login_confirmacao.setMaximumSize(QtCore.QSize(16777215, 150))
        self.login_confirmacao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_confirmacao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_confirmacao.setObjectName("login_confirmacao")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.login_confirmacao)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.login_confirmacao)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.login_confirmacao)
        self.frame_2.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(230, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.login_pushButton_logar = QtWidgets.QPushButton(self.frame_2)
        self.login_pushButton_logar.setMinimumSize(QtCore.QSize(230, 50))
        self.login_pushButton_logar.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login_pushButton_logar.setFont(font)
        self.login_pushButton_logar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_pushButton_logar.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"        \n"
"    color: rgb(240, 233, 249);\n"
"    background-color: rgb(255, 144, 14);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(207, 110, 0);\n"
"    color: rgb(240, 233, 249);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"")
        self.login_pushButton_logar.setObjectName("login_pushButton_logar")
        self.verticalLayout_2.addWidget(self.login_pushButton_logar)
        self.login_pushButton_entrar_cadastro = QtWidgets.QPushButton(self.frame_2)
        self.login_pushButton_entrar_cadastro.setMaximumSize(QtCore.QSize(300, 16777215))
        self.login_pushButton_entrar_cadastro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_pushButton_entrar_cadastro.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    border-image: url(:/Close_Image/cil-x.png);\n"
"    background-position: center;\n"
"    \n"
"    color: rgb(0,127,255);\n"
"}\n"
"\n"
"\n"
"")
        self.login_pushButton_entrar_cadastro.setObjectName("login_pushButton_entrar_cadastro")
        self.verticalLayout_2.addWidget(self.login_pushButton_entrar_cadastro)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.login_confirmacao)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.login_confirmacao)
        self.verticalLayout.addWidget(self.login_conteudo)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login do Funcionario"))
        self.login_lineEdit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.login_lineEdit_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.login_pushButton_logar.setText(_translate("MainWindow", "login"))
        self.login_pushButton_entrar_cadastro.setText(_translate("MainWindow", "Cadastrar-se"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
